name: not-birman CI Testing 

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE**'
      - 'notebooks/**'
      - 'scripts/utils/**'
      - 'scripts/wsl/**'
      - '**/*.ipynb'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/*.md'
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'LICENSE**'
      - 'notebooks/**'
      - 'scripts/utils/**'
      - 'scripts/wsl/**'
      - '**/*.ipynb'
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/*.md'
  workflow_dispatch:

jobs:
  birman-tests:
    name: not-birman-15-tests
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
  
      - name: run pytests 
        run: |
          docker exec riallto_docker /bin/bash -c "source ~/.bashrc; python3 -m pip install .; python3 -m pytest ./tests"
